[package]
name = "pathfinder-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
# poise = "0.5"
serenity = { version = "0.11"}
sqlite = "0.32"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
